//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.05 at 12:56:32 PM CEST 
//


package net.bobah.ufixj.repository.repo;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{}entityAttribGrp"/>
 *       &lt;attribute name="id" type="{}CategoryID_t" />
 *       &lt;attribute name="FIXMLFileName" type="{}Name_t" />
 *       &lt;attribute name="notReqXML" type="{}BOOL_t" />
 *       &lt;attribute name="generateImplFile" type="{}BOOL_t" />
 *       &lt;attribute name="componentType" type="{}CatComponentType_t" />
 *       &lt;attribute name="section" type="{}SectionID_t" />
 *       &lt;attribute name="volume" type="{}Volume_t" />
 *       &lt;attribute name="includeFile" type="{}CatIncludeFile_t" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "category")
public class Category {

    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "FIXMLFileName")
    protected String fixmlFileName;
    @XmlAttribute(name = "notReqXML")
    protected Short notReqXML;
    @XmlAttribute(name = "generateImplFile")
    protected Short generateImplFile;
    @XmlAttribute(name = "componentType")
    protected CatComponentTypeT componentType;
    @XmlAttribute(name = "section")
    protected SectionIDT section;
    @XmlAttribute(name = "volume")
    protected String volume;
    @XmlAttribute(name = "includeFile")
    protected CatIncludeFileT includeFile;
    @XmlAttribute(name = "added")
    protected String added;
    @XmlAttribute(name = "addedEP")
    protected BigInteger addedEP;
    @XmlAttribute(name = "changeType")
    protected ChangeTypeT changeType;
    @XmlAttribute(name = "custom")
    protected Short custom;
    @XmlAttribute(name = "deprecated")
    protected String deprecated;
    @XmlAttribute(name = "deprecatedEP")
    protected BigInteger deprecatedEP;
    @XmlAttribute(name = "elaborationTextId")
    protected String elaborationTextId;
    @XmlAttribute(name = "issue")
    protected String issue;
    @XmlAttribute(name = "lastModified")
    protected String lastModified;
    @XmlAttribute(name = "replaced")
    protected String replaced;
    @XmlAttribute(name = "replacedEP")
    protected BigInteger replacedEP;
    @XmlAttribute(name = "supported")
    protected Short supported;
    @XmlAttribute(name = "textId")
    protected String textId;
    @XmlAttribute(name = "updated")
    protected String updated;
    @XmlAttribute(name = "updatedEP")
    protected BigInteger updatedEP;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the fixmlFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIXMLFileName() {
        return fixmlFileName;
    }

    /**
     * Sets the value of the fixmlFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIXMLFileName(String value) {
        this.fixmlFileName = value;
    }

    /**
     * Gets the value of the notReqXML property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getNotReqXML() {
        return notReqXML;
    }

    /**
     * Sets the value of the notReqXML property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setNotReqXML(Short value) {
        this.notReqXML = value;
    }

    /**
     * Gets the value of the generateImplFile property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getGenerateImplFile() {
        return generateImplFile;
    }

    /**
     * Sets the value of the generateImplFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setGenerateImplFile(Short value) {
        this.generateImplFile = value;
    }

    /**
     * Gets the value of the componentType property.
     * 
     * @return
     *     possible object is
     *     {@link CatComponentTypeT }
     *     
     */
    public CatComponentTypeT getComponentType() {
        return componentType;
    }

    /**
     * Sets the value of the componentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatComponentTypeT }
     *     
     */
    public void setComponentType(CatComponentTypeT value) {
        this.componentType = value;
    }

    /**
     * Gets the value of the section property.
     * 
     * @return
     *     possible object is
     *     {@link SectionIDT }
     *     
     */
    public SectionIDT getSection() {
        return section;
    }

    /**
     * Sets the value of the section property.
     * 
     * @param value
     *     allowed object is
     *     {@link SectionIDT }
     *     
     */
    public void setSection(SectionIDT value) {
        this.section = value;
    }

    /**
     * Gets the value of the volume property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVolume() {
        return volume;
    }

    /**
     * Sets the value of the volume property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVolume(String value) {
        this.volume = value;
    }

    /**
     * Gets the value of the includeFile property.
     * 
     * @return
     *     possible object is
     *     {@link CatIncludeFileT }
     *     
     */
    public CatIncludeFileT getIncludeFile() {
        return includeFile;
    }

    /**
     * Sets the value of the includeFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatIncludeFileT }
     *     
     */
    public void setIncludeFile(CatIncludeFileT value) {
        this.includeFile = value;
    }

    /**
     * Gets the value of the added property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdded() {
        return added;
    }

    /**
     * Sets the value of the added property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdded(String value) {
        this.added = value;
    }

    /**
     * Gets the value of the addedEP property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAddedEP() {
        return addedEP;
    }

    /**
     * Sets the value of the addedEP property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAddedEP(BigInteger value) {
        this.addedEP = value;
    }

    /**
     * Gets the value of the changeType property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeTypeT }
     *     
     */
    public ChangeTypeT getChangeType() {
        return changeType;
    }

    /**
     * Sets the value of the changeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeTypeT }
     *     
     */
    public void setChangeType(ChangeTypeT value) {
        this.changeType = value;
    }

    /**
     * Gets the value of the custom property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getCustom() {
        return custom;
    }

    /**
     * Sets the value of the custom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setCustom(Short value) {
        this.custom = value;
    }

    /**
     * Gets the value of the deprecated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeprecated() {
        return deprecated;
    }

    /**
     * Sets the value of the deprecated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeprecated(String value) {
        this.deprecated = value;
    }

    /**
     * Gets the value of the deprecatedEP property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDeprecatedEP() {
        return deprecatedEP;
    }

    /**
     * Sets the value of the deprecatedEP property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDeprecatedEP(BigInteger value) {
        this.deprecatedEP = value;
    }

    /**
     * Gets the value of the elaborationTextId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElaborationTextId() {
        return elaborationTextId;
    }

    /**
     * Sets the value of the elaborationTextId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElaborationTextId(String value) {
        this.elaborationTextId = value;
    }

    /**
     * Gets the value of the issue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssue() {
        return issue;
    }

    /**
     * Sets the value of the issue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssue(String value) {
        this.issue = value;
    }

    /**
     * Gets the value of the lastModified property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastModified() {
        return lastModified;
    }

    /**
     * Sets the value of the lastModified property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastModified(String value) {
        this.lastModified = value;
    }

    /**
     * Gets the value of the replaced property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplaced() {
        return replaced;
    }

    /**
     * Sets the value of the replaced property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplaced(String value) {
        this.replaced = value;
    }

    /**
     * Gets the value of the replacedEP property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getReplacedEP() {
        return replacedEP;
    }

    /**
     * Sets the value of the replacedEP property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setReplacedEP(BigInteger value) {
        this.replacedEP = value;
    }

    /**
     * Gets the value of the supported property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getSupported() {
        return supported;
    }

    /**
     * Sets the value of the supported property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setSupported(Short value) {
        this.supported = value;
    }

    /**
     * Gets the value of the textId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextId() {
        return textId;
    }

    /**
     * Sets the value of the textId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextId(String value) {
        this.textId = value;
    }

    /**
     * Gets the value of the updated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdated() {
        return updated;
    }

    /**
     * Sets the value of the updated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdated(String value) {
        this.updated = value;
    }

    /**
     * Gets the value of the updatedEP property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUpdatedEP() {
        return updatedEP;
    }

    /**
     * Sets the value of the updatedEP property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUpdatedEP(BigInteger value) {
        this.updatedEP = value;
    }

}
