//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.05 at 12:56:32 PM CEST 
//


package net.bobah.ufixj.repository.repo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}messageEntity_t">
 *       &lt;attribute name="inlined" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="implMinOccurs" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="implMaxOccurs" type="{http://www.w3.org/2001/XMLSchema}short" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
public class ComponentRef
    extends MessageEntityT
{

    @XmlAttribute(name = "inlined")
    protected Boolean inlined;
    @XmlAttribute(name = "implMinOccurs")
    protected Short implMinOccurs;
    @XmlAttribute(name = "implMaxOccurs")
    protected Short implMaxOccurs;

    /**
     * Gets the value of the inlined property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInlined() {
        return inlined;
    }

    /**
     * Sets the value of the inlined property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInlined(Boolean value) {
        this.inlined = value;
    }

    /**
     * Gets the value of the implMinOccurs property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getImplMinOccurs() {
        return implMinOccurs;
    }

    /**
     * Sets the value of the implMinOccurs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setImplMinOccurs(Short value) {
        this.implMinOccurs = value;
    }

    /**
     * Gets the value of the implMaxOccurs property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getImplMaxOccurs() {
        return implMaxOccurs;
    }

    /**
     * Sets the value of the implMaxOccurs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setImplMaxOccurs(Short value) {
        this.implMaxOccurs = value;
    }

}
