//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.05 at 12:56:32 PM CEST 
//


package net.bobah.ufixj.repository.repo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}messageEntity_t">
 *       &lt;attribute name="implMinLength" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="implMaxLength" type="{http://www.w3.org/2001/XMLSchema}short" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
public class FieldRef
    extends MessageEntityT
{

    @XmlAttribute(name = "implMinLength")
    protected Short implMinLength;
    @XmlAttribute(name = "implMaxLength")
    protected Short implMaxLength;

    /**
     * Gets the value of the implMinLength property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getImplMinLength() {
        return implMinLength;
    }

    /**
     * Sets the value of the implMinLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setImplMinLength(Short value) {
        this.implMinLength = value;
    }

    /**
     * Gets the value of the implMaxLength property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getImplMaxLength() {
        return implMaxLength;
    }

    /**
     * Sets the value of the implMaxLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setImplMaxLength(Short value) {
        this.implMaxLength = value;
    }

}
