//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.05 at 12:56:32 PM CEST 
//


package net.bobah.ufixj.repository.repo;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}enum" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}entityAttribGrp"/>
 *       &lt;attribute name="id" use="required" type="{}id_t" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="associatedDataTag" type="{}id_t" />
 *       &lt;attribute name="abbrName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="baseCategory" type="{}CategoryID_t" />
 *       &lt;attribute name="baseCategoryAbbrName" type="{}Name_t" />
 *       &lt;attribute name="notReqXML" type="{}BOOL_t" />
 *       &lt;attribute name="notUsed" type="{}BOOL_t" />
 *       &lt;attribute name="enumDatatype" type="{}Tag_t" />
 *       &lt;attribute name="unionDataType" type="{}UnionDataType_t" />
 *       &lt;attribute name="implMinLength" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="implMaxLength" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="replacedByField" type="{}Tag_t" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "_enum"
})
@XmlRootElement(name = "field")
public class Field {

    @XmlElement(name = "enum")
    protected List<Enum> _enum;
    @XmlAttribute(name = "id", required = true)
    protected BigInteger id;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "type", required = true)
    protected String type;
    @XmlAttribute(name = "associatedDataTag")
    protected BigInteger associatedDataTag;
    @XmlAttribute(name = "abbrName")
    protected String abbrName;
    @XmlAttribute(name = "baseCategory")
    protected String baseCategory;
    @XmlAttribute(name = "baseCategoryAbbrName")
    protected String baseCategoryAbbrName;
    @XmlAttribute(name = "notReqXML")
    protected Short notReqXML;
    @XmlAttribute(name = "notUsed")
    protected Short notUsed;
    @XmlAttribute(name = "enumDatatype")
    protected BigInteger enumDatatype;
    @XmlAttribute(name = "unionDataType")
    protected UnionDataTypeT unionDataType;
    @XmlAttribute(name = "implMinLength")
    protected Short implMinLength;
    @XmlAttribute(name = "implMaxLength")
    protected Short implMaxLength;
    @XmlAttribute(name = "replacedByField")
    protected BigInteger replacedByField;
    @XmlAttribute(name = "added")
    protected String added;
    @XmlAttribute(name = "addedEP")
    protected BigInteger addedEP;
    @XmlAttribute(name = "changeType")
    protected ChangeTypeT changeType;
    @XmlAttribute(name = "custom")
    protected Short custom;
    @XmlAttribute(name = "deprecated")
    protected String deprecated;
    @XmlAttribute(name = "deprecatedEP")
    protected BigInteger deprecatedEP;
    @XmlAttribute(name = "elaborationTextId")
    protected String elaborationTextId;
    @XmlAttribute(name = "issue")
    protected String issue;
    @XmlAttribute(name = "lastModified")
    protected String lastModified;
    @XmlAttribute(name = "replaced")
    protected String replaced;
    @XmlAttribute(name = "replacedEP")
    protected BigInteger replacedEP;
    @XmlAttribute(name = "supported")
    protected Short supported;
    @XmlAttribute(name = "textId")
    protected String textId;
    @XmlAttribute(name = "updated")
    protected String updated;
    @XmlAttribute(name = "updatedEP")
    protected BigInteger updatedEP;

    /**
     * Gets the value of the enum property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the enum property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEnum().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Enum }
     * 
     * 
     */
    public List<Enum> getEnum() {
        if (_enum == null) {
            _enum = new ArrayList<Enum>();
        }
        return this._enum;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the associatedDataTag property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAssociatedDataTag() {
        return associatedDataTag;
    }

    /**
     * Sets the value of the associatedDataTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAssociatedDataTag(BigInteger value) {
        this.associatedDataTag = value;
    }

    /**
     * Gets the value of the abbrName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbbrName() {
        return abbrName;
    }

    /**
     * Sets the value of the abbrName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbbrName(String value) {
        this.abbrName = value;
    }

    /**
     * Gets the value of the baseCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseCategory() {
        return baseCategory;
    }

    /**
     * Sets the value of the baseCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseCategory(String value) {
        this.baseCategory = value;
    }

    /**
     * Gets the value of the baseCategoryAbbrName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseCategoryAbbrName() {
        return baseCategoryAbbrName;
    }

    /**
     * Sets the value of the baseCategoryAbbrName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseCategoryAbbrName(String value) {
        this.baseCategoryAbbrName = value;
    }

    /**
     * Gets the value of the notReqXML property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getNotReqXML() {
        return notReqXML;
    }

    /**
     * Sets the value of the notReqXML property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setNotReqXML(Short value) {
        this.notReqXML = value;
    }

    /**
     * Gets the value of the notUsed property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getNotUsed() {
        return notUsed;
    }

    /**
     * Sets the value of the notUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setNotUsed(Short value) {
        this.notUsed = value;
    }

    /**
     * Gets the value of the enumDatatype property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEnumDatatype() {
        return enumDatatype;
    }

    /**
     * Sets the value of the enumDatatype property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEnumDatatype(BigInteger value) {
        this.enumDatatype = value;
    }

    /**
     * Gets the value of the unionDataType property.
     * 
     * @return
     *     possible object is
     *     {@link UnionDataTypeT }
     *     
     */
    public UnionDataTypeT getUnionDataType() {
        return unionDataType;
    }

    /**
     * Sets the value of the unionDataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnionDataTypeT }
     *     
     */
    public void setUnionDataType(UnionDataTypeT value) {
        this.unionDataType = value;
    }

    /**
     * Gets the value of the implMinLength property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getImplMinLength() {
        return implMinLength;
    }

    /**
     * Sets the value of the implMinLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setImplMinLength(Short value) {
        this.implMinLength = value;
    }

    /**
     * Gets the value of the implMaxLength property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getImplMaxLength() {
        return implMaxLength;
    }

    /**
     * Sets the value of the implMaxLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setImplMaxLength(Short value) {
        this.implMaxLength = value;
    }

    /**
     * Gets the value of the replacedByField property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getReplacedByField() {
        return replacedByField;
    }

    /**
     * Sets the value of the replacedByField property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setReplacedByField(BigInteger value) {
        this.replacedByField = value;
    }

    /**
     * Gets the value of the added property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdded() {
        return added;
    }

    /**
     * Sets the value of the added property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdded(String value) {
        this.added = value;
    }

    /**
     * Gets the value of the addedEP property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAddedEP() {
        return addedEP;
    }

    /**
     * Sets the value of the addedEP property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAddedEP(BigInteger value) {
        this.addedEP = value;
    }

    /**
     * Gets the value of the changeType property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeTypeT }
     *     
     */
    public ChangeTypeT getChangeType() {
        return changeType;
    }

    /**
     * Sets the value of the changeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeTypeT }
     *     
     */
    public void setChangeType(ChangeTypeT value) {
        this.changeType = value;
    }

    /**
     * Gets the value of the custom property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getCustom() {
        return custom;
    }

    /**
     * Sets the value of the custom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setCustom(Short value) {
        this.custom = value;
    }

    /**
     * Gets the value of the deprecated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeprecated() {
        return deprecated;
    }

    /**
     * Sets the value of the deprecated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeprecated(String value) {
        this.deprecated = value;
    }

    /**
     * Gets the value of the deprecatedEP property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDeprecatedEP() {
        return deprecatedEP;
    }

    /**
     * Sets the value of the deprecatedEP property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDeprecatedEP(BigInteger value) {
        this.deprecatedEP = value;
    }

    /**
     * Gets the value of the elaborationTextId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElaborationTextId() {
        return elaborationTextId;
    }

    /**
     * Sets the value of the elaborationTextId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElaborationTextId(String value) {
        this.elaborationTextId = value;
    }

    /**
     * Gets the value of the issue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssue() {
        return issue;
    }

    /**
     * Sets the value of the issue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssue(String value) {
        this.issue = value;
    }

    /**
     * Gets the value of the lastModified property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastModified() {
        return lastModified;
    }

    /**
     * Sets the value of the lastModified property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastModified(String value) {
        this.lastModified = value;
    }

    /**
     * Gets the value of the replaced property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplaced() {
        return replaced;
    }

    /**
     * Sets the value of the replaced property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplaced(String value) {
        this.replaced = value;
    }

    /**
     * Gets the value of the replacedEP property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getReplacedEP() {
        return replacedEP;
    }

    /**
     * Sets the value of the replacedEP property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setReplacedEP(BigInteger value) {
        this.replacedEP = value;
    }

    /**
     * Gets the value of the supported property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getSupported() {
        return supported;
    }

    /**
     * Sets the value of the supported property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setSupported(Short value) {
        this.supported = value;
    }

    /**
     * Gets the value of the textId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextId() {
        return textId;
    }

    /**
     * Sets the value of the textId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextId(String value) {
        this.textId = value;
    }

    /**
     * Gets the value of the updated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdated() {
        return updated;
    }

    /**
     * Sets the value of the updated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdated(String value) {
        this.updated = value;
    }

    /**
     * Gets the value of the updatedEP property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUpdatedEP() {
        return updatedEP;
    }

    /**
     * Sets the value of the updatedEP property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUpdatedEP(BigInteger value) {
        this.updatedEP = value;
    }

}
