//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.05 at 12:56:32 PM CEST 
//


package net.bobah.ufixj.repository.repo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}abbreviations" minOccurs="0"/>
 *         &lt;element ref="{}datatypes"/>
 *         &lt;element ref="{}categories" minOccurs="0"/>
 *         &lt;element ref="{}sections" minOccurs="0"/>
 *         &lt;element ref="{}fields"/>
 *         &lt;element ref="{}components"/>
 *         &lt;element ref="{}messages"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{}Version_t" />
 *       &lt;attribute name="guid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="customVersion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fixml" use="required" type="{}BOOL_t" />
 *       &lt;attribute name="hasComponents" use="required" type="{}BOOL_t" />
 *       &lt;attribute name="specUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "abbreviations",
    "datatypes",
    "categories",
    "sections",
    "fields",
    "components",
    "messages"
})
@XmlRootElement(name = "fix")
public class Fix {

    protected Abbreviations abbreviations;
    @XmlElement(required = true)
    protected Datatypes datatypes;
    protected Categories categories;
    protected Sections sections;
    @XmlElement(required = true)
    protected Fields fields;
    @XmlElement(required = true)
    protected Components components;
    @XmlElement(required = true)
    protected Messages messages;
    @XmlAttribute(name = "version", required = true)
    protected String version;
    @XmlAttribute(name = "guid")
    protected String guid;
    @XmlAttribute(name = "customVersion")
    protected String customVersion;
    @XmlAttribute(name = "fixml", required = true)
    protected short fixml;
    @XmlAttribute(name = "hasComponents", required = true)
    protected short hasComponents;
    @XmlAttribute(name = "specUrl")
    @XmlSchemaType(name = "anyURI")
    protected String specUrl;

    /**
     * Gets the value of the abbreviations property.
     * 
     * @return
     *     possible object is
     *     {@link Abbreviations }
     *     
     */
    public Abbreviations getAbbreviations() {
        return abbreviations;
    }

    /**
     * Sets the value of the abbreviations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Abbreviations }
     *     
     */
    public void setAbbreviations(Abbreviations value) {
        this.abbreviations = value;
    }

    /**
     * Gets the value of the datatypes property.
     * 
     * @return
     *     possible object is
     *     {@link Datatypes }
     *     
     */
    public Datatypes getDatatypes() {
        return datatypes;
    }

    /**
     * Sets the value of the datatypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Datatypes }
     *     
     */
    public void setDatatypes(Datatypes value) {
        this.datatypes = value;
    }

    /**
     * Gets the value of the categories property.
     * 
     * @return
     *     possible object is
     *     {@link Categories }
     *     
     */
    public Categories getCategories() {
        return categories;
    }

    /**
     * Sets the value of the categories property.
     * 
     * @param value
     *     allowed object is
     *     {@link Categories }
     *     
     */
    public void setCategories(Categories value) {
        this.categories = value;
    }

    /**
     * Gets the value of the sections property.
     * 
     * @return
     *     possible object is
     *     {@link Sections }
     *     
     */
    public Sections getSections() {
        return sections;
    }

    /**
     * Sets the value of the sections property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sections }
     *     
     */
    public void setSections(Sections value) {
        this.sections = value;
    }

    /**
     * Gets the value of the fields property.
     * 
     * @return
     *     possible object is
     *     {@link Fields }
     *     
     */
    public Fields getFields() {
        return fields;
    }

    /**
     * Sets the value of the fields property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fields }
     *     
     */
    public void setFields(Fields value) {
        this.fields = value;
    }

    /**
     * Gets the value of the components property.
     * 
     * @return
     *     possible object is
     *     {@link Components }
     *     
     */
    public Components getComponents() {
        return components;
    }

    /**
     * Sets the value of the components property.
     * 
     * @param value
     *     allowed object is
     *     {@link Components }
     *     
     */
    public void setComponents(Components value) {
        this.components = value;
    }

    /**
     * Gets the value of the messages property.
     * 
     * @return
     *     possible object is
     *     {@link Messages }
     *     
     */
    public Messages getMessages() {
        return messages;
    }

    /**
     * Sets the value of the messages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Messages }
     *     
     */
    public void setMessages(Messages value) {
        this.messages = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the guid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuid() {
        return guid;
    }

    /**
     * Sets the value of the guid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuid(String value) {
        this.guid = value;
    }

    /**
     * Gets the value of the customVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomVersion() {
        return customVersion;
    }

    /**
     * Sets the value of the customVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomVersion(String value) {
        this.customVersion = value;
    }

    /**
     * Gets the value of the fixml property.
     * 
     */
    public short getFixml() {
        return fixml;
    }

    /**
     * Sets the value of the fixml property.
     * 
     */
    public void setFixml(short value) {
        this.fixml = value;
    }

    /**
     * Gets the value of the hasComponents property.
     * 
     */
    public short getHasComponents() {
        return hasComponents;
    }

    /**
     * Sets the value of the hasComponents property.
     * 
     */
    public void setHasComponents(short value) {
        this.hasComponents = value;
    }

    /**
     * Gets the value of the specUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecUrl() {
        return specUrl;
    }

    /**
     * Sets the value of the specUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecUrl(String value) {
        this.specUrl = value;
    }

}
