//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.05 at 12:56:32 PM CEST 
//


package net.bobah.ufixj.repository.repo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.bobah.ufixj.repository.repo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RepeatingGroup_QNAME = new QName("", "repeatingGroup");
    private final static QName _MessageEntity_QNAME = new QName("", "messageEntity");
    private final static QName _ComponentRef_QNAME = new QName("", "componentRef");
    private final static QName _FieldRef_QNAME = new QName("", "fieldRef");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.bobah.ufixj.repository.repo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FixRepository }
     * 
     */
    public FixRepository createFixRepository() {
        return new FixRepository();
    }

    /**
     * Create an instance of {@link Fix }
     * 
     */
    public Fix createFix() {
        return new Fix();
    }

    /**
     * Create an instance of {@link Abbreviations }
     * 
     */
    public Abbreviations createAbbreviations() {
        return new Abbreviations();
    }

    /**
     * Create an instance of {@link Abbreviation }
     * 
     */
    public Abbreviation createAbbreviation() {
        return new Abbreviation();
    }

    /**
     * Create an instance of {@link Datatypes }
     * 
     */
    public Datatypes createDatatypes() {
        return new Datatypes();
    }

    /**
     * Create an instance of {@link Datatype }
     * 
     */
    public Datatype createDatatype() {
        return new Datatype();
    }

    /**
     * Create an instance of {@link XML }
     * 
     */
    public XML createXML() {
        return new XML();
    }

    /**
     * Create an instance of {@link Categories }
     * 
     */
    public Categories createCategories() {
        return new Categories();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link Sections }
     * 
     */
    public Sections createSections() {
        return new Sections();
    }

    /**
     * Create an instance of {@link Section }
     * 
     */
    public Section createSection() {
        return new Section();
    }

    /**
     * Create an instance of {@link Fields }
     * 
     */
    public Fields createFields() {
        return new Fields();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link Enum }
     * 
     */
    public Enum createEnum() {
        return new Enum();
    }

    /**
     * Create an instance of {@link Components }
     * 
     */
    public Components createComponents() {
        return new Components();
    }

    /**
     * Create an instance of {@link Component }
     * 
     */
    public Component createComponent() {
        return new Component();
    }

    /**
     * Create an instance of {@link MessageEntityT }
     * 
     */
    public MessageEntityT createMessageEntityT() {
        return new MessageEntityT();
    }

    /**
     * Create an instance of {@link Messages }
     * 
     */
    public Messages createMessages() {
        return new Messages();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link Languages }
     * 
     */
    public Languages createLanguages() {
        return new Languages();
    }

    /**
     * Create an instance of {@link Language }
     * 
     */
    public Language createLanguage() {
        return new Language();
    }

    /**
     * Create an instance of {@link ComponentRef }
     * 
     */
    public ComponentRef createComponentRef() {
        return new ComponentRef();
    }

    /**
     * Create an instance of {@link RepeatingGroup }
     * 
     */
    public RepeatingGroup createRepeatingGroup() {
        return new RepeatingGroup();
    }

    /**
     * Create an instance of {@link FieldRef }
     * 
     */
    public FieldRef createFieldRef() {
        return new FieldRef();
    }

    /**
     * Create an instance of {@link DatatypeXMLT }
     * 
     */
    public DatatypeXMLT createDatatypeXMLT() {
        return new DatatypeXMLT();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RepeatingGroup }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "repeatingGroup", substitutionHeadNamespace = "", substitutionHeadName = "messageEntity")
    public JAXBElement<RepeatingGroup> createRepeatingGroup(RepeatingGroup value) {
        return new JAXBElement<RepeatingGroup>(_RepeatingGroup_QNAME, RepeatingGroup.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageEntityT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "messageEntity")
    public JAXBElement<MessageEntityT> createMessageEntity(MessageEntityT value) {
        return new JAXBElement<MessageEntityT>(_MessageEntity_QNAME, MessageEntityT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComponentRef }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "componentRef", substitutionHeadNamespace = "", substitutionHeadName = "messageEntity")
    public JAXBElement<ComponentRef> createComponentRef(ComponentRef value) {
        return new JAXBElement<ComponentRef>(_ComponentRef_QNAME, ComponentRef.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FieldRef }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fieldRef", substitutionHeadNamespace = "", substitutionHeadName = "messageEntity")
    public JAXBElement<FieldRef> createFieldRef(FieldRef value) {
        return new JAXBElement<FieldRef>(_FieldRef_QNAME, FieldRef.class, null, value);
    }

}
