//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.05 at 12:56:32 PM CEST 
//


package net.bobah.ufixj.repository.repo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}messageEntity_t">
 *       &lt;sequence>
 *         &lt;element ref="{}messageEntity" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="implMinOccurs" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="implMaxOccurs" type="{http://www.w3.org/2001/XMLSchema}short" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "messageEntity"
})
public class RepeatingGroup
    extends MessageEntityT
{

    @XmlElementRef(name = "messageEntity", type = JAXBElement.class, required = false)
    protected List<JAXBElement<? extends MessageEntityT>> messageEntity;
    @XmlAttribute(name = "implMinOccurs")
    protected Short implMinOccurs;
    @XmlAttribute(name = "implMaxOccurs")
    protected Short implMaxOccurs;

    /**
     * Gets the value of the messageEntity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the messageEntity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessageEntity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link ComponentRef }{@code >}
     * {@link JAXBElement }{@code <}{@link FieldRef }{@code >}
     * {@link JAXBElement }{@code <}{@link RepeatingGroup }{@code >}
     * {@link JAXBElement }{@code <}{@link MessageEntityT }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends MessageEntityT>> getMessageEntity() {
        if (messageEntity == null) {
            messageEntity = new ArrayList<JAXBElement<? extends MessageEntityT>>();
        }
        return this.messageEntity;
    }

    /**
     * Gets the value of the implMinOccurs property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getImplMinOccurs() {
        return implMinOccurs;
    }

    /**
     * Sets the value of the implMinOccurs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setImplMinOccurs(Short value) {
        this.implMinOccurs = value;
    }

    /**
     * Gets the value of the implMaxOccurs property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getImplMaxOccurs() {
        return implMaxOccurs;
    }

    /**
     * Sets the value of the implMaxOccurs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setImplMaxOccurs(Short value) {
        this.implMaxOccurs = value;
    }

}
