//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.05 at 12:57:11 PM CEST 
//


package net.bobah.ufixj.repository.phrases;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SectionID_t.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SectionID_t">
 *   &lt;restriction base="{}Name_t">
 *     &lt;enumeration value="Session"/>
 *     &lt;enumeration value="PreTrade"/>
 *     &lt;enumeration value="Trade"/>
 *     &lt;enumeration value="PostTrade"/>
 *     &lt;enumeration value="Infrastructure"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SectionID_t")
@XmlEnum
public enum SectionIDT {

    @XmlEnumValue("Session")
    SESSION("Session"),
    @XmlEnumValue("PreTrade")
    PRE_TRADE("PreTrade"),
    @XmlEnumValue("Trade")
    TRADE("Trade"),
    @XmlEnumValue("PostTrade")
    POST_TRADE("PostTrade"),
    @XmlEnumValue("Infrastructure")
    INFRASTRUCTURE("Infrastructure"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    SectionIDT(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SectionIDT fromValue(String v) {
        for (SectionIDT c: SectionIDT.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
