//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.05 at 12:57:11 PM CEST 
//


package net.bobah.ufixj.repository.phrases;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UnionDataType_t.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="UnionDataType_t">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Qty"/>
 *     &lt;enumeration value="Reserved100Plus"/>
 *     &lt;enumeration value="Reserved1000Plus"/>
 *     &lt;enumeration value="Reserved4000Plus"/>
 *     &lt;enumeration value="Tenor"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "UnionDataType_t")
@XmlEnum
public enum UnionDataTypeT {

    @XmlEnumValue("Qty")
    QTY("Qty"),
    @XmlEnumValue("Reserved100Plus")
    RESERVED_100_PLUS("Reserved100Plus"),
    @XmlEnumValue("Reserved1000Plus")
    RESERVED_1000_PLUS("Reserved1000Plus"),
    @XmlEnumValue("Reserved4000Plus")
    RESERVED_4000_PLUS("Reserved4000Plus"),
    @XmlEnumValue("Tenor")
    TENOR("Tenor");
    private final String value;

    UnionDataTypeT(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static UnionDataTypeT fromValue(String v) {
        for (UnionDataTypeT c: UnionDataTypeT.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
