//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.05 at 12:57:11 PM CEST 
//


package net.bobah.ufixj.repository.phrases;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VolumeName_t.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="VolumeName_t">
 *   &lt;restriction base="{}Name_t">
 *     &lt;enumeration value="Volume1"/>
 *     &lt;enumeration value="Volume2"/>
 *     &lt;enumeration value="Volume3"/>
 *     &lt;enumeration value="Volume4"/>
 *     &lt;enumeration value="Volume5"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "VolumeName_t")
@XmlEnum
public enum VolumeNameT {

    @XmlEnumValue("Volume1")
    VOLUME_1("Volume1"),
    @XmlEnumValue("Volume2")
    VOLUME_2("Volume2"),
    @XmlEnumValue("Volume3")
    VOLUME_3("Volume3"),
    @XmlEnumValue("Volume4")
    VOLUME_4("Volume4"),
    @XmlEnumValue("Volume5")
    VOLUME_5("Volume5");
    private final String value;

    VolumeNameT(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VolumeNameT fromValue(String v) {
        for (VolumeNameT c: VolumeNameT.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
